### ISSUE TITLE
Disclosure of the Tableau server URL in the console

### ISSUE THREAD

**Issue by paulo-j-m-nunes** [nfqsolutions/ngx-tableau#38]
Is it possible to get ride of the console log where the Tableau server URL is disclosed?

**Comment by hmartos** [comment]
Hi @paulo-j-m-nunes!

It is definitely possible to get rid of these console logs or show them only if a 'debug' mode is enabled, I will take note of it for the next release.

Anyway, be aware that the Tableau visualization is embedded in an iframe, so anybody can see the Tableau server URL by inspecting the page.

I will let you know when I publish the new release.

Thanks!

**Comment by hmartos** [comment]
Hi  @paulo-j-m-nunes,

I just wanted to let you know that this issue is fixed and a new option `debugMode` has been added to the component to show the old log traces, as explained in the [documentation](https://github.com/nfqsolutions/ngx-tableau#debugmode).

I hope this helps!
