### ISSUE TITLE
How can I load tableau.x.x.x.min.js file from dedicated server

### ISSUE THREAD

**Issue by josephbellow** [nfqsolutions/ngx-tableau#42]
Hello team

Once I use this lib, it loads min.js file from https://public.tableau.com
Can I load this file from dedicated server?

**Comment by hmartos** [comment]
Hi @josephbellow,

It wasn't possible to load a custom Tableau JavaScript API up to version 2.0.1 of this module, with this [Tableau 2.9.1 JS API](https://public.tableau.com/javascripts/api/tableau-2.9.1.min.js) being loaded by default. 

I have just released a new version 2.1.0 of this module with this feature, as this was a quick change, and now you can load a custom Tableau JS API using the input `tableauJsApiUrl` as shown in [this example](https://stackblitz.com/edit/ngx-tableau?file=src%2Fapp%2Fapp.component.html).

Please, take into account that the [Tableau JavaScript API is being deprecated](https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api.htm) in favor of the [Tableau Embedding API v3](https://help.tableau.com/current/api/embedding_api/en-us/index.html), which expose a web component to do exactly what this Angular module do. Here there is an official [migration guide](https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_migration_guide.html) that might be useful.

I hope this helps!
