### ISSUE TITLE
Filter parameters doesn't work with viz

### ISSUE THREAD

**Issue by vikas-nexcom** [nfqsolutions/ngx-tableau#7]
Hi guys, 

Thanks for the very helpful package. It has definitely made my life as easier. I am trying to embed a Tableau dashboard with filter parameters but it doesn't seem to work.
I have tried with the given example as well:

```
<ngx-tableau
  tableauVizUrl="https://public.tableau.com/views/SuperSampleSuperstore/SuperDescriptive"
  filters="{ Parameter3: 'Central' }"
></ngx-tableau>
```

https://stackblitz.com/edit/ngx-tableau-dvczzy?file=src/app/app.component.html

I get the following error in the console:

```
dashboard/dashboard.component.html:23:17 - error TS2322: Type 'string' is not assignable to type 'object'.
``` 

What am I doing wrong? Any help will be really appreciated.

**Comment by hmartos** [comment]
Hi @vikas-nexcom! 

Thank you very for your feedback and for raising an issue.

I have checked the example and it seems that the attribute `filters` should be passed between brackets `[filters]`. Anyway, I have not been able to make this example work. As this is a public Tableau without much information, I don't know the exact name of the parameters. 

Fortunately, I found another public [Tableau Viz](https://public.tableau.com/app/profile/marniemo/viz/URLParameters-TableauPublic/UseURLParameterstoFiltertoRegion) with filter parameters to create an [example](https://stackblitz.com/edit/ngx-tableau-otsa1e?file=src/app/app.component.html).

```html
<ngx-tableau
  tableauVizUrl="https://public.tableau.com/views/URLParameters-TableauPublic/UseURLParameterstoFiltertoRegion"
  [filters]="{ Region: 'AsiaPac' }"
></ngx-tableau>
```

You can also load the filters from a variable in the controller, passing the name of the variable in the controller in the filters attribute like in this [example](https://stackblitz.com/edit/ngx-tableau-q7upai?file=src%2Fapp%2Fapp.component.html)

```html
<ngx-tableau
  tableauVizUrl="https://public.tableau.com/views/URLParameters-TableauPublic/UseURLParameterstoFiltertoRegion"
  [filters]="filters"
></ngx-tableau>
```

Please check it out and let me know if you have further problems.

Thank you very much!

**Comment by vikas-nexcom** [comment]
Hi @hmartos 

That solves the issue. Thanks very much for the prompt response. Keep up the great work!

**Comment by hmartos** [comment]
Thank you for using the module and for your feedback.

I'm closing the issue, feel free to raise any other issue!
