### ISSUE TITLE
tableauVizUrl with ticket for embedding a private dashboard

### ISSUE THREAD

**Issue by vikas-nexcom** [nfqsolutions/ngx-tableau#8]
Hi @hmartos,

Thanks for the help with the previous issue. I have got one more issue that has come up recently. I am trying to embed a private dashboard in Angular. As mentioned in the docs, I have added an IP to the server and can get a ticket. I am doing the following based on the examples you have provided.  
```
<ngx-tableau
         tableauVizUrl="http://**someserver**/views/TL_QA_real_new/TL?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link">
         ticket="someticket"
</ngx-tableau> 
```

This doesn't work. Either, it shows me the empty screen or says the ticket is not valid.  I understand the ticket lasts only one time. Is this the correct approach?

I have tried a different approach as well. If in the browser, I do the following : 

```
http://**someserver**/trusted/put_ticket_here/views/TL_QA_real_new/TL?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link">
```
I can see the dashboard but if I do that within angular, I see the login screen.  

```
<ngx-tableau
    tableauVizUrl='http://**someserver**/trusted/put_ticket_here/views/TL_QA_real_new/TL?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link>'
</ngx-tableau>
```

Is there anything wrong here? Any suggesations from your side.

**Comment by hmartos** [comment]
Hi again, @vikas-nexcom 

To embed a private Tableau dashboard there are a few considerations to take into account.

I've seen you have already added the IP to the server, and I assume you can obtain valid trusted tickets (not -1).

One thing to consider is that, by default, Tableau allows trusted tickets to “live” without being redeemed for up to 180 seconds. Any unused ticket is not redeemable 180 seconds after the ticket was created. You can change this timeout as shown in the [documentation](https://kb.tableau.com/articles/issue/changing-the-expiration-timeout-of-trusted-tickets).

Another thing to consider is that if your Tableau visualization uses a private data source requiring credentials, you should embed the data source password in the connection to avoid the sign in screen. I think this topic is not very well documented, but I can share this [page](https://help.tableau.com/current/pro/desktop/en-us/publishing_sharing_authentication.htm) and this other [page](https://help.tableau.com/current/server/en-us/connections_modify.htm) that could help you.

Following these steps, you should be able to see the embedded Tableau visualization with this approach:

```html
<ngx-tableau
  serverUrl="http://**someserver**"
  report="TL_QA_real_new/TL"
  ticket="put_ticket_here"
></ngx-tableau>
```

Or directly embedding the generated URL:

```html
<ngx-tableau
  tableauVizUrl ="http://**someserver**/trusted/put_ticket_here/views/TL_QA_real_new/TL"
></ngx-tableau>
```

Please, let me know if this helps you.

**Comment by vikas-nexcom** [comment]
@hmartos Thanks for the prompt answer once again. Yes, I can generate tickets with no problem and I am using a fresh ticket for each change. 

I am trying the direct approach. It works if I try that in the browser but it shows me a tableau login screen, which I don't understand. 

Here is the error: 

```
core.js:5980 ERROR TypeError: Cannot read properties of null (reading 'width')
    at M.handleVizLoad (tableau-2.2.2.min.js:10)
    at D.$1 (tableau-2.2.2.min.js:10)
    at D.<anonymous> (tableau-2.2.2.min.js:10)
    at O.delegate [as $7] (tableau-2.2.2.min.js:4)
    at O.$1 (tableau-2.2.2.min.js:8)
    at delegate (tableau-2.2.2.min.js:4)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28289)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
defaultErrorLogger @ core.js:5980
handleError @ core.js:6028
next @ core.js:28901
schedulerFn @ core.js:25666
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25656
(anonymous) @ core.js:28324
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:28229
onHandleError @ core.js:28324
handleError @ zone-evergreen.js:368
runTask @ zone-evergreen.js:170
invokeTask @ zone-evergreen.js:480
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647
```

![Screenshot from 2021-11-12 14-42-13](https://user-images.githubusercontent.com/74184952/141476641-6669282e-effe-4f90-85cf-a35221a9e69c.png)

**Comment by hmartos** [comment]
I can see from the screenshot that the visualization is loaded, so I would say that the problem why you are seeing the Sign in screen is in the token generation.

To fix this problem, I recommend you check the following items:

- Ensure that you have [added the IP of the web server](https://help.tableau.com/current/server/en-us/trusted_auth_trustIP.htm) from which the Tableau ticket is being requested
- Ensure that the username used to request a Tableau ticket through the API is correct. If you are using a site other than _Default_, you will need to add it as a parameter to the ticket request as indicated in the [documentation](https://help.tableau.com/current/server/en-us/trusted_auth_webrequ.htm)
- Check the [authorization](https://help.tableau.com/current/server/en-us/security_authorize.htm) and [permissions](https://help.tableau.com/current/server/en-us/permissions.htm#projectpermissions) of the user on the sites, views and data sources that you are embedding
- Review the authentication flow that is shown in the diagram in the [documentation](https://help.tableau.com/current/server/en-us/trusted_auth.htm)

As for the CORS issue you are commenting on, I know very few details of your implementation, but I would say that CORS should not be a problem for integrating a visualization in the browser with this module, although it may be a problem in obtaining the ticket from your REST API.

For Tableau private visualization embedding, which is the main purpose of this module, I strongly recommend using the **serverUrl**, **report** and **ticket** configuration options to avoid having to build the embed URL.

```html
<ngx-tableau
  serverUrl="https://myprivatetableau.mycompany.com"
  report="SomeWorkbook/SomeView"
  ticket="SomeTicket" // If you are using a ticket from a controller => [ticket]="variableContainingTicket"
 //site="SomeSite" // Only if you are using a site different from Default 
></ngx-tableau>
```

I hope this helps, let me know if it has been useful.

**Comment by vikas-nexcom** [comment]
Hi @hmartos , 

I think I have figured out the reason for my issue, it was because server would need HTTPS in order to work [(see here).](https://community.tableau.com/s/question/0D54T00000TqOvrSAF/tableau-server-keeps-showing-login-screen-for-embedded-javascript). I am hoping this will solve the login screen problem.  I just want to ask a quick question about ticket generation. Do you know what's wrong with this service method: 

```
generateTableauTicket() {

  const httpOptions = {
    headers: new HttpHeaders({
      "Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"
    }),
  };
  const body = {
    username: 'some-username'
  };
  return this.http.post('/tableauApi', body, httpOptions)

```
It always returns -1. It is not because of IP and permission. On the log on the tableau server, I see that it says missing client_ip or username. I tried supplying both but it gives the same -1. 

However, if I use fetch I get the ticket, it works. I don't understand what's missing in the above method:
```
generateTableauTicket() {

  var myHeaders = new Headers();
  myHeaders.append("Content-Type", "application/x-www-form-urlencoded");

  var urlencoded = new URLSearchParams();
  urlencoded.append("username", "some-username");

  var requestOptions = {
    'method': 'POST',
    headers: myHeaders,
    body: urlencoded
  };

return fetch("/tableauApi", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
 ```

Thanks for all the help.

**Comment by hmartos** [comment]
Hi again @vikas-nexcom,

Sorry for the late response, I have been very busy this week.

I can see in your first code block that you are sending a request with a `Content-Type: 'application/x-www-form-urlencoded'`, which is the correct Content-Type for this request, **but you are sending a body with a JSON object**.

I think that sending a correct body will solve the problem with the first code block (this is why the second code block works):

```javascript
generateTableauTicket() {
  const httpOptions = {
    headers: new HttpHeaders({
      "Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"
    }),
  };

  // URL encoded body - equivalent to const body = 'username=some-username'
  var body = new URLSearchParams();
  body.append("username", "some-username");

  return this.http.post('/tableauApi', body, httpOptions)
}
```

Let me know if this helps.

I think this issue is a very good reference for anybody embedding Tableau private reports, although it is not directly related to the module `ngx-tableau`, so I will close it when you confirm that you have no more problems.

**Comment by vikas-nexcom** [comment]
Hi @hmartos 
That definitely helped. Everything works now. Thanks very much for the help.
